### ISSUE TITLE
不再支持带花括号的数组和字符串偏移访问语法

### ISSUE THREAD

**Issue by Yujunjie0224** [alucardwind/blackhack#1]
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /www/wwwroot/jielovemin/wp-content/themes/blackhack-master/saetv2.ex.class.php on line 457

**Comment by alucardwind** [comment]
不清楚你有没有成功申请到微博的外联权限，如果没有请参照readme里的方法

如果已经申请到，我的PHP版本是7.4.8，并没有碰到相关问题

另外这个问题，我在网上搜索了一下，可能修改saetv2.ex.class.php on line 457

if( in_array($parameter, array('pic', 'image')) && $value{0} == '@' ) {
修改为
if( in_array($parameter, array('pic', 'image')) && $value[0] == '@' ) {

试试看，也许能行。我自己修改后，没发现什么变化。

最后，关于该问题，发生在主题所引用的微博PHP SDK相关组件问题。需要联系https://github.com/xiaosier/libweibo
